### ISSUE TITLE
API Key not validating

### ISSUE THREAD

**Issue by Phet0902** [BigBlueBit/BitMEXAssistant#27]
Since Install version 0.0.16, the API Key at the begin of each new session of BitMexAssistant is not validating anymore. Both platforms, Real and Test. Ne
![bitmexassistant_api_validation](https://user-images.githubusercontent.com/37608624/42861241-62cafda4-8a84-11e8-8b6f-e2c097163b4b.JPG)
w API Key on BitMex/ Test BitMex had been created

**Comment by denotexist** [comment]
I have the same problem.

**Comment by BigBlueBit** [comment]
nikita is correct.  The nonce was getting too large because of how it was calculated by the default connector provided by bitmex.  I just pushed an update, v0.0.161 which should start the nonce off much lower, but I do recommend that you create a new API key/secret for this version because I changed how the nonce is calculated, which may not work with older API info since the nonce has to increase.
